<main id="home" class="p-3">
    <h1 class="text-center m-5">Ze blog</h1>
    <section class="my-5">
        <h2>Design</h2>
        <ul class="row p-0">
            
            <?php 
            
            $post = null;
            foreach($design as $key => $design_item) { 
            echo $key;
            $post = $key;
            
            ?>
                <li class="col m-1">
                    <article class="card">
                        <header class="card-header p-0">
                            <img src="https://picsum.photos/id/1/550/250" class="card-img-top" alt="" />
                            <h3 class="card-title px-2 py-3">
                                <?= $design_item['title'] ?>
                            </h3>
                        </header>
                        <section class="card-body p-2">
                            <p class="card-text">
                                <?php echo $design_item['excerpt'] ?>
                            </p>
                        </section>
                        <footer class="p-2">
                            <a href="index.php?route=article" class="btn btn-primary">Lire l'article</a>
                        </footer>
                    </article>
                </li>
                
            <?php } ?>
            
        </ul>
    </section>
    <section class="my-5">
        <h2>Development</h2>
        <ul class="row p-0">
            
            <?php foreach($dev as $dev_item) { ?>
            
            <li class="col m-1">
                <article class="card">
                    <header class="card-header p-0">
                        <img src="https://picsum.photos/id/32/550/250" class="card-img-top" alt="" />
                        <h3 class="card-title px-2 py-3">
                            <?php echo $dev_item['title'] ?>
                        </h3>
                    </header>
                    <section class="card-body p-2">
                        <p class="card-text">
                             <?php echo $dev_item['excerpt'] ?>
                        </p>
                    </section>
                    <footer class="p-2">
                        <a href="index.php?route=article" class="btn btn-primary">Lire l'article</a>
                    </footer>
                </article>
            </li>
            
            <?php } ?>
            </ul>
    </section>
            
            <section class="my-5">
        <h2>Accessibility</h2>
        <ul class="row p-0">
            
            <?php foreach($access as $access_item) { ?>
            
            <li class="col m-1">
                <article class="card">
                    <header class="card-header p-0">
                        <img src="https://picsum.photos/id/44/550/250" class="card-img-top" alt="" />
                        <h3 class="card-title px-2 py-3">
                            <?php echo $access_item['title'] ?>
                        </h3>
                    </header>
                    <section class="card-body p-2">
                        <p class="card-text">
                            <?php echo $access_item['excerpt'] ?>
                        </p>
                    </section>
                    <footer class="p-2">
                        <a href="index.php?route=article" class="btn btn-primary">Lire l'article</a>
                    </footer>
                </article>
            </li>
            
            <?php } ?>
            
            </ul>
    </section>
            
</main>