<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <title>Cinépotes</title>
        <meta name="title" content="Cinépotes" />
        <meta name="description" content="Critiques de films par une bande de potes" />
        <meta name="author" content="Gaëllan Sifflepignon" />
        <meta name="referrer" content="origin" />
        <meta name="og:title" content="Cinépotes" />
        <meta name="og:description" content="Critiques de films par une bande de potes" />
        <meta name="og:locale" content="fr_FR" />
        <link rel="stylesheet" href="assets/css/style.css" />
    </head>
    <?php
        require "page.phtml";
    ?>
</html>